Deploy to vercel using webhook

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -98,36 +98,41 @@ jobs:
       #     echo "Quality Gate status did not become available in time."
       #     exit 1
 
-      - name: Check Quality Gate for short live branches
+      # - name: Check Quality Gate for short live branches
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
+      #   run: |
+      #     max_retries=3   # Adjust retry count for faster checks
+      #     delay=5         # Adjust delay for quicker retries
+      #     count=0
+
+      #     while [ "$count" -lt "$max_retries" ]; do
+      #       # Fetch the Quality Gate status
+      #       status=$(curl -s -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=SPMGroup7Key&branch=rayTest" | jq -r .projectStatus.status)
+      #       echo "Attempt $((count+1)): Quality Gate status: $status"
+
+      #       if [ "$status" == "OK" ]; then
+      #         echo "Quality Gate passed"
+      #         exit 0
+      #       elif [ "$status" == "ERROR" ]; then
+      #         echo "Quality Gate failed"
+      #         exit 1
+      #       else
+      #         echo "Quality Gate status is not available yet, retrying in $delay seconds..."
+      #       fi
+
+      #       count=$((count+1))
+      #       sleep $delay
+      #     done
+
+      #     echo "Quality Gate status did not become available in time."
+      #     exit 1
+      - name: Trigger Vercel Deploy
+        # if: success()
         env:
-          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
+          DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
         run: |
-          max_retries=3   # Adjust retry count for faster checks
-          delay=5         # Adjust delay for quicker retries
-          count=0
-
-          while [ "$count" -lt "$max_retries" ]; do
-            # Fetch the Quality Gate status
-            status=$(curl -s -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=SPMGroup7Key&branch=rayTest" | jq -r .projectStatus.status)
-            echo "Attempt $((count+1)): Quality Gate status: $status"
-
-            if [ "$status" == "OK" ]; then
-              echo "Quality Gate passed"
-              exit 0
-            elif [ "$status" == "ERROR" ]; then
-              echo "Quality Gate failed"
-              exit 1
-            else
-              echo "Quality Gate status is not available yet, retrying in $delay seconds..."
-            fi
-
-            count=$((count+1))
-            sleep $delay
-          done
-
-          echo "Quality Gate status did not become available in time."
-          exit 1
-
+          curl -X POST "$DEPLOY_HOOK_URL"
   # build-and-test:
   #   runs-on: ubuntu-latest
 
